name: LogSense AI Dağıtım (K3s)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: GitHub Container Registry'ye Giriş Yap
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Backend İmajını Oluştur ve Yükle
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/logsense-backend:latest

      - name: Frontend İmajını Oluştur ve Yükle
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/logsense-frontend:latest
          build-args: |
            NEXT_PUBLIC_API_URL=http://${{ secrets.SERVER_IP }}:30000

      - name: Deployment Dosyasını Hazırla (IP Güncelle)
        run: |
          sed -i "s/<SUNUCU_IP>/${{ secrets.SERVER_IP }}/g" deployment.yaml

      - name: Dosyayı Sunucuya Gönder (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deployment.yaml"
          target: "~/logsense-deploy"

      - name: Sunucuda Dağıtımı Uygula (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/logsense-deploy
            # K3s yetki sorunu için chmod yaptığınızı varsayıyorum
            kubectl apply -f deployment.yaml
            kubectl rollout restart deployment backend -n logsense
            kubectl rollout restart deployment frontend -n logsense
